#!/bin/sh

current_tag="$(git describe --exact-match --tags)"

if [ -n "$current_tag" ]
then
	echo "Current tag is $current_tag, building pages..."
	./.minicycle/pages || exit 2
else
	echo "No tag found, skipping building pages."
fi

exec ./.minicycle/tests

