#!/bin/sh

# This script builds and publishes pages

set -e

echo CHECKING REPO

set +e
git remote | grep gh-pages

if [ "$?" != 0 ]
then
	echo 'Remote `gh-pages` not found!'
	echo 'Create a `gh-pages` remote in this repo'
	echo 'with ssh url that has write access to `gh-pages` branch. '
fi
set -e

echo RUNNING DOCS PIPELINE
./podman/test-all.sh docs

echo SAVING ARTIFACT
cp -r --reflink=auto ./podman/output/docs "$MINICYCLE_ARTIFACTS/docs"

echo ADDING PAGES TO GIT
git reset --hard
git branch gh-pages || true
git checkout gh-pages
rm -rf *
cp -r --reflink=auto "$MINICYCLE_ARTIFACTS/docs" ./docs
git add --all
git commit --allow-empty -m "autocommit from Mitakihara on $(date)" 
git push --set-upstream gh-pages gh-pages


