FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN \
	apt update && \
	apt install -y \
		python3.9 \
		python3.9-dev \
		python3.9-venv \
		wget \
		&& \
		:

RUN \
	python3.9 -m venv /venv && \
	:

ARG REQS_FILE=requirements.noextras.txt
COPY ${REQS_FILE} ${REQS_FILE}

RUN \
	. /venv/bin/activate && \
	pip install -r ${REQS_FILE} && \
	:



