FROM debian:bookworm

ARG DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN \
	apt update && \
	apt install -y \
		python3.11 \
		python3.11-dev \
		python3.11-venv \
		wget \
		&& \
		:

RUN \
	python3.11 -m venv /venv && \
	:

ARG REQS_FILE=requirements.noextras.txt
COPY ${REQS_FILE} ${REQS_FILE}

RUN \
	. /venv/bin/activate && \
	pip install -r ${REQS_FILE} && \
	:




