name: Make release and docs

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # create release + upload assets
  packages: read    # pull image from GHCR

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository }}:main
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark repo as safe for git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Build sdist
        run: |
          set -e
          . /venv/bin/activate
          python -m build --sdist

      - name: List built artifacts (debug)
        run: ls -lah dist

      - name: Generate and Deploy Doxygen Docs
        run: |
          set -e
          rm -rf docs
          . /venv/bin/activate
          ./scripts/GenerateDocs.py

      - name: List built docs (debug)
        run: ls -lah docs

      - name: Make docs tarball
        run: |
          set -e
          tagname=$(git describe --tags --abbrev=0)
          tar cf - docs | xz > "gateau-docs-${tagname}.tar.xz"

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            dist/*.tar.gz
            gateau-docs-*.tar*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  pages:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

